### PR TITLE
style: fixed footer, added backgrounds to cards, small improvements t…

### PR DESCRIPTION
**Pull request by ha-anna**
fixed footer, added backgrounds to cards, small improvements to margin, padding etc

### CODE REVIEW

**Comment by sukyungdev** [comment]
LGTM

**Comment by genelorenzSarmiento0408** [comment]
Use shorthands in the padding

**Comment by genelorenzSarmiento0408** [comment]
ok.

**Comment by genelorenzSarmiento0408** [comment]
Merging.... (the `1em 1em`) does not make a difference

**Pull request merged**
